// generateSitemap.js
import fs from 'fs';
import { SitemapStream, streamToPromise } from 'sitemap';

// Define your URLs based on the routes from App.jsx
const urls = [
    { url: '/', changefreq: 'daily', priority: 1.0, lastmod: new Date().toISOString() },
    { url: '/about', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
    { url: '/skills', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
    { url: '/qualification', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
    { url: '/services', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
    { url: '/portfolio', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
    { url: '/project', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
    { url: '/testimonials', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
    { url: '/contact', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
    { url: '/background-remover', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
    { url: '/viral-linkedin-post-generator', changefreq: 'monthly', priority: 0.8, lastmod: new Date().toISOString() },
];

// Function to generate XML sitemap
const generateSitemapXML = async () => {
    const sitemapStream = new SitemapStream({ hostname: 'https://www.smitparekh.studio' });

    // Add URLs to the sitemap
    urls.forEach(url => sitemapStream.write(url));
    sitemapStream.end();

    // Write the XML to a file
    const sitemapXML = await streamToPromise(sitemapStream).then(data => data.toString());
    fs.writeFileSync('./public/sitemap.xml', sitemapXML);
    console.log('Sitemap XML generated.');
};

// Function to generate HTML sitemap
// Function to generate HTML sitemap
const generateSitemapHTML = () => {
    const totalPages = urls.length; // Count total pages
    const lastUpdated = new Date().toLocaleDateString(); // Get current date

    let htmlContent = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>www.smitparekh.studio Site Map - Generated by www.xml-sitemaps.com</title>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <style type="text/css">
      body {
        background-color: #fff;
        font-family: "Roboto", "Helvetica", "Arial", sans-serif;
        margin: 0;
      }
      #top {
        background-color: #b1d1e8;
        font-size: 16px;
        padding-bottom: 40px;
      }
      nav {
        font-size: 24px;
        margin: 0px 30px 0px;
        border-bottom-left-radius: 6px;
        border-bottom-right-radius: 6px;
        background-color: #f3f3f3;
        color: #666;
        box-shadow: 0 10px 20px -12px rgba(0, 0, 0, 0.42), 0 3px 20px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
        padding: 10px 0;
        text-align: center;
        z-index: 1;
      }
      h3 {
        margin: auto;
        padding: 10px;
        max-width: 600px;
        color: #666;
      }
      h3 span {
        float: right;
      }
      h3 a {
        font-weight: normal;
        display: block;
      }
      #cont {
        position: relative;
        border-radius: 6px;
        box-shadow: 0 16px 24px 2px rgba(0, 0, 0, 0.14), 0 6px 30px 5px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
        background: #f3f3f3;
        margin: -20px 30px 0px 30px;
        padding: 20px;
      }
      a:link,
      a:visited {
        color: #0180af;
        text-decoration: underline;
      }
      a:hover {
        color: #666;
      }
      #footer {
        padding: 10px;
        text-align: center;
      }
      ul {
        margin: 0px;
        padding: 0px;
        list-style: none;
      }
      li {
        margin: 0px;
      }
      li ul {
        margin-left: 20px;
      }
      .lhead {
        background: #ddd;
        padding: 10px;
        margin: 10px 0px;
      }
      .lcount {
        padding: 0px 10px;
      }
      .lpage {
        border-bottom: #ddd 1px solid;
        padding: 5px;
      }
      .last-page {
        border: none;
      }
    </style>
  </head>
  <body>
    <div id="top">
      <nav>www.smitparekh.studio HTML Site Map</nav>
      <h3>
        <span>Last updated: ${lastUpdated}<br />Total pages: ${totalPages}</span>
        <a href="https://www.smitparekh.studio">www.smitparekh.studio Homepage</a>
      </h3>
    </div>
    <div id="cont">
      <ul class="level-0">
        <li class="lhead">/ <span class="lcount">${totalPages} pages</span></li>
  `;

    urls.forEach((url) => {
        htmlContent += `
        <li class="lpage last-page">
          <a href="https://www.smitparekh.studio${url.url}" title="${url.url}">${url.url}</a>
        </li>
      `;
    });

    htmlContent += `
      </ul>
      <!--
Please note:
You are not allowed to remove the copyright notice below.
Thank you!
www.xml-sitemaps.com
-->
    </div>
    <div id="footer">
      Page created with <a target="_blank" href="https://www.xml-sitemaps.com">Google XML sitemap and html sitemaps generator</a> | Copyright &copy; 2005-2024 XML-Sitemaps.com
    </div>
  </body>
</html>
  `;

    fs.writeFileSync('./public/sitemap.html', htmlContent);
    console.log('Sitemap HTML generated.');
};

// Function to generate ROR (RSS) XML
const generateRORXML = async () => {
    const rorXML = `
    <?xml version="1.0" encoding="UTF-8"?>
    <rss version="2.0">
      <channel>
        <title>Your Website Title</title>
        <link>https://www.smitparekh.studio</link>
        <description>Your website description</description>
        ${urls.map(url => `
          <item>
            <title>${url.url}</title>
            <link>https://www.smitparekh.studio${url.url}</link>
            <description>${url.url} description.</description>
            <pubDate>${new Date().toUTCString()}</pubDate>
          </item>
        `).join('')}
      </channel>
    </rss>
  `;

    fs.writeFileSync('./public/ror.xml', rorXML);
    console.log('ROR XML generated.');
};

// Run the functions
const generateSitemaps = async () => {
    await generateSitemapXML();
    generateSitemapHTML();
    await generateRORXML();
};

generateSitemaps().catch(console.error);
